// Jenkins Pipeline Script
pipeline {
    agent any 

    tools {
        gradle 'gradle-8'
    }

    environment {
        DOCKERHUB_USERNAME = 'pkun2014' 
        IMAGE_NAME = "${DOCKERHUB_USERNAME}/pollService"
        DB_HOST=credentials('pollService-db-host')
        DB_PORT=credentials('pollService-db-port')
        DB_NAME=credentials('pollService-db-name')
        DB_USERNAME=credentials('pollService-db-username')
        DB_PASSWORD=credentials('pollService-db-password')
        REDIS_HOST=credentials('redis-host')
        REDIS_PORT=credentials('redis-port')
        KAFKA_BOOTSTRAP_SERVERS=credentials('kafka-bootstrap-servers')
        JWT_SECRET_KEY = credentials('jwt-secret-key')
    }

    stages {
        stage('Checkout') { 
            steps {
                git branch: 'master', credentialsId: 'pkun2_jenkins', url: 'https://github.com/pkun2/everypoll-msa.git'
            }
        }

        stage('Build') { 
            steps {
                sh './gradlew :authService:clean build --info'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('pollService') {
                    script {
                        
                        def customImage = docker.build("${IMAGE_NAME}:${env.BUILD_NUMBER}", ".")
                        
                        docker.withRegistry('https://registry.hub.docker.com', 'pkun2014_jenkins') {
                            customImage.push()
                        }
                    }
                }
            }
        }
    }
}