// Jenkins Pipeline Script
pipeline {
    agent any 

    tools {
        gradle 'gradle-8'
    }

    environment {
        DOCKERHUB_USERNAME = 'pkun2014' 
        IMAGE_NAME = "${DOCKERHUB_USERNAME}/pollService"
    }

    stages {
        stage('Checkout') { 
            steps {
                git branch: 'master', credentialsId: 'github', url: 'https://github.com/pkun2/everypoll-msa.git'
            }
        }

        stage('Prepare Config File') {
            steps {
               configFileProvider([configFile(fileId: 'pollService-dotenv', variable: 'envPropsPath')]) {
                    script {
                        def props = readProperties file: env.envPropsPath

                        def envVars = props.collect { key, value -> "${key}=${value}" }

                        withEnv(envVars) {
                            echo "데이터베이스 호스트: ${env.DB_HOST}:${env.DB_PORT}"
                            echo "레디스 호스트: ${env.REDIS_HOST}"
                            echo "카프카 서버: ${env.KAFKA_BOOTSTRAP_SERVERS}"
                        }
                    }
                } 
            }
        }

        stage('Build') { 
            steps {
                sh './gradlew :pollService:clean build --info'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('pollService') {
                    script {
                        
                        def customImage = docker.build("${IMAGE_NAME}:${env.BUILD_NUMBER}", ".")
                        
                        docker.withRegistry('https://registry.hub.docker.com', 'docker') {
                            customImage.push()
                        }
                    }
                }
            }
        }
    }
}