pipeline {
    agent any 

    tools {
        gradle 'gradle-8'
    }

    environment {
        DOCKERHUB_USERNAME = 'pkun2014' 
        IMAGE_NAME = "${DOCKERHUB_USERNAME}/authService"
    }

    stages {
        stage('Checkout') { 
            steps {
                git branch: 'master', credentialsId: 'github', url: 'https://github.com/pkun2/everypoll-msa.git'
            }
        }

        stage('Prepare Config File') {
            steps {
                configFileProvider([configFile(fileId: 'authService-dotenv', targetLocation: '.env')]) {
                    sh 'echo "Configuration file is ready."'
                    sh 'cat .env' 
                    
                    injectEnvironment(propertiesFilePath: '.env')

                    sh './gradlew build'
                }
                
                sh 'echo "File does not exist outside the block."'
                sh 'ls -la'
            }
        }

        stage('Build') { 
            steps {
                sh './gradlew :pollService:clean build --info'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('authService') {
                    script {
                        
                        def customImage = docker.build("${IMAGE_NAME}:${env.BUILD_NUMBER}", ".")
                        
                        docker.withRegistry('https://registry.hub.docker.com', 'docker') {
                            customImage.push()
                        }
                    }
                }
            }
        }
    }
}