// Jenkins Pipeline Script
pipeline {
    agent any 

    tools {
        gradle 'gradle-8'
    }

    environment {
        DOCKERHUB_USERNAME = 'pkun2014' 
        IMAGE_NAME = "${DOCKERHUB_USERNAME}/authService"
    }

    stages {
        stage('Checkout') { 
            steps {
                git branch: 'master', credentialsId: 'pkun2_jenkins', url: 'https://github.com/pkun2/everypoll-msa.git'
            }
        }

        stage('Build') { 
            steps {
                sh './gradlew :auth-service:clean build --info'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('authService') {
                    script {
                        
                        def customImage = docker.build("${IMAGE_NAME}:${env.BUILD_NUMBER}", ".")
                        
                        docker.withRegistry('https://registry.hub.docker.com', 'pkun2014_jenkins') {
                            customImage.push()
                        }
                    }
                }
            }
        }
    }
}