pipeline {
    agent any 

    tools {
        gradle 'gradle-8'
    }

    environment {
        DOCKERHUB_USERNAME = 'pkun2014' 
        IMAGE_NAME = "${DOCKERHUB_USERNAME}/authService"
        DB_HOST=credentials('authService-db-host')
        DB_PORT=credentials('authService-db-port')
        DB_NAME=credentials('authService-db-name')
        DB_USERNAME=credentials('authService-db-username')
        DB_PASSWORD=credentials('authService-db-password')
        REDIS_HOST=credentials('redis-host')
        REDIS_PORT=credentials('redis-port')
        KAFKA_BOOTSTRAP_SERVERS=credentials('kafka-bootstrap-servers')
        JWT_SECRET_KEY = credentials('jwt-secret-key')
    }

    stages {
        stage('Checkout') { 
            steps {
                git branch: 'master', credentialsId: 'pkun2_jenkins', url: 'https://github.com/pkun2/everypoll-msa.git'
            }
        }

        stage('Prepare Config File') {
            steps {
                configFileProvider([configFile(fileId: 'authService-dotenv', targetLocation: '.env')]) {
                    sh 'echo "Configuration file is ready."'
                    sh 'cat .env' 
                    
                    sh './gradlew build'
                }
                
                sh 'echo "File does not exist outside the block."'
                sh 'ls -la'
            }
        }

        stage('Build') { 
            steps {
                sh './gradlew :pollService:clean build --info'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('authService') {
                    script {
                        
                        def customImage = docker.build("${IMAGE_NAME}:${env.BUILD_NUMBER}", ".")
                        
                        docker.withRegistry('https://registry.hub.docker.com', 'pkun2014_jenkins') {
                            customImage.push()
                        }
                    }
                }
            }
        }
    }
}